name = "DecisionFocusedLearningAlgorithms"
uuid = "46d52364-bc3b-4fac-a992-eb1d3ef2de15"
authors = ["Members of JuliaDecisionFocusedLearning and contributors"]
version = "0.1.0"

[workspace]
projects = ["docs", "test"]

[deps]
DecisionFocusedLearningBenchmarks = "2fbe496a-299b-4c81-bab5-c44dfc55cf20"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
InferOpt = "4846b161-c94e-4150-8dac-c7ae193c601f"
MLUtils = "f1d291b0-491e-4a28-83b9-f70985020b54"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"
ValueHistories = "98cad3c8-aec3-5f06-8e41-884608649ab7"

[compat]
DecisionFocusedLearningBenchmarks = "0.4"
Flux = "0.16.5"
InferOpt = "0.7.1"
MLUtils = "0.4.8"
ProgressMeter = "1.11.0"
Random = "1.11.0"
Statistics = "1.11.1"
UnicodePlots = "3.8.1"
ValueHistories = "0.5.4"
julia = "1.11"
